### ISSUE TITLE
Closing connection with tls-mirage raises an End_of_file exception

### ISSUE THREAD

**Issue by juanchanco** [mirage/mirage-http#28]
Firstly, I apologize, I'm not sure this is *your* bug, but this is where is manifests for me and hopefully you all might know better where the responsibility should go.

Anyway, I have a Mirage unikernel serving a webservice using cohttp. Everything is fine in unix (both http and https) but when running in Xen, the first https requests raises an error and the whole thing dies.
```
Fatal error: exception (Failure "TLS.server_of_flow: End-of-file!")
Raised at file "format.ml", line 241, characters 41-52
Called from file "format.ml", line 482, characters 6-24
Mirage exiting with status 2
Do_exit called!
```

This didn't happen with older versions on mirage-http (2.5.1 and earlier). I've tracked it down to "listen" in http_mirage.ml. Starting with 2.5.2 it started calling `Channel.close` after handling the request. This causes the Channel to flush, which writes to it's internal Flow. Digging further, it seems that by this point, when using tls_mirage, the Flow is already in a closed state, and raises an End_of_file exception. Since apparently none of the other Flows (at least unix and non-https xen) do this, I'm not sure if it's "expected" behavior or not.

**Comment by hannesm** [comment]
which mirage-net-xen do you use?  It seems the fix for https://github.com/mirage/mirage-net-xen/issues/39 was never released in the 1.6 line.  I still use the 1.4.2 release (or nowadays the 1.4 branch -- try it with `opam pin add mirage-net-xen https://github.com/mirage/mirage-net-xen.git#1.4`).

**Comment by juanchanco** [comment]
I was using 1.6.1 and you are correct, pinning to the 1.4 branch made the problem go away. Alternately, adding an Lwt.async_exception_hook to ignore the End_of_file exception also works (without having to downgrade), though that seems a bit crude.

That mirage-net-xen bug (#39) is closed now. It was hard to tell from the chain what the final decision was about where best to handle the exception. It actually seems (to me) that it should be in mirage-channel. One would expect that Channel.close wouldn't raise an exception if the underlying Flow is already closed. Maybe I should re-file this bug there.

**Comment by juanchanco** [comment]
I have created a new bug here https://github.com/mirage/mirage-channel/issues/12
