### ISSUE TITLE
Rename the module

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-http#9]
`HTTP` seems quite a widely used name -- we should rename it to `Cohttp_mirage.. Only issue with that is that we should change the mirage tool and all the code examples ...

**Comment by avsm** [comment]
Why change the code examples?  We could still alias it in the `mirage` tool.

**Comment by samoht** [comment]
Some of the code examples use the `HTTP` module manually I think. But maybe this is not so widespread, need to check.

**Comment by avsm** [comment]
Yeah, as happened with `CONSOLE`

**Comment by samoht** [comment]
The fix is now in trunk and will be released as 2.2.0
